version: '3.7'

services:
#    autorizadorvr:
#      image: autorizadorvr:0.0.1-SNAPSHOT
#      restart: always
#      ports:
#        - 8080:8080
#      links:
#        - mysql
      mysql:
      image: mysql:5.7
      hostname: mysql
      container_name: mysql
      restart: always
      ports:
       - 3306:3306
      environment:
        MYSQL_DATABASE: miniautorizador
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'